<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../FeatureService/Harmonee.FeatureService.Application/Harmonee.FeatureService.Application.csproj" />
    <ProjectReference Include="../Harmonee.FamilyService.Domain/Harmonee.FamilyService.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Harmonee.Shared.Infrastructure\Harmonee.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
  </ItemGroup>

</Project>
